# Generated by Django 4.2.17 on 2025-03-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="наименование объекта"
                    ),
                ),
            ],
            options={
                "verbose_name": "объект строительства",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construct_service.building",
                        verbose_name="объект",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construct_service.section",
                        verbose_name="родительская секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "секция сметы",
            },
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название расценки"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Работа", "Work"), ("Материал", "Material")],
                        max_length=8,
                        verbose_name="тип расценки",
                    ),
                ),
                (
                    "count",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        verbose_name="количество материала",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="цена за единицу товара",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="расценка может принадлежать только той секции, у которой указан parent",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construct_service.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "расценка сметы",
            },
        ),
    ]
